# CodeRestaurant2021 Space-Invaders Main Workflow with github Actions


name: Build and Release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '11'
          java-package: jdk
          architecture: x64

      - name: Create 'out' directory
        run: mkdir out

      - name: Compile Java file to 'out' directory
        run: javac ./src/engine/*.java ./src/entity/*.java ./src/screen/*.java -d ./out

      - name: Copy resource file to compliled folder
        run: cp -R res/. ./out

      - name: Make an executable jar file (create/verbose/filename/manifest)
        run: jar cvfm invaders.jar ./src/META-INF/MANIFEST.MF -C ./out/ .

      - name: Release jar file
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.BUILD_TOKEN }}
          file: ./invaders.jar
          asset_name: invaders.jar
          tag: ${{ github.ref }}
          overwrite: true
          body: "This is my release text"
